config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root to: 'pages#home'
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  resources :reviews
  
 # login -> new session
  #logout -> close session
  #post login -> create session
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index, :like]
  before_action :require_same_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  
  def new
    
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])  
  end
  
  def show
    @review = Review.find(params[:id])
  end
  
  def index
    @reviews = Review.paginate(page: params[:page], per_page: 4)
  end
  
  def create
    @review = Review.new(review_params)
    @review.chef = current_user

    newRecipe = @review.recipe
    existReview = Review.where(:recipe => newRecipe, :chef => current_user)
    if existReview.exists?
     flash[:danger] = "You can only create a review for this recipe once"
     render :new
    else
           if @review.save
           flash[:success] = "Your review was created successfully!"
           redirect_to reviews_path
           else
           render :new
           end
    end       
  end

  def update
    if @review.update(review_params)
      flash[:success] = "Your review was updated successfully!"
      redirect_to reviews_path
    else
      render :edit
    end  
  end

  private 
  
  def review_params
     params.require(:review).permit(:title, :recipe_id, :review_text, :rating)  
  end
  
  def set_review
    @review = Review.find(params[:id])     
  end
  
  def destroy
        Review.find(params[:id]).destroy
        flash[:success] = "Review Deleted"
        redirect_to recipes_path
  end
        
  def require_same_user
    if current_user != @review.chef and !current_user.admin?
    flash[:danger] = "You can only edit your own reviews"  
    redirect_to reviews_path
    end
  end
  
  def admin_user
    redirect_to reviews_path unless current_user.admin?
  end
  

end

app/views/reviews/_form.html.erb
<div class="row">
   <div class="well col-md-8 col-md-offset-2">
     <%= form_for @review do |f| %> 
        <%= f.label :title %>:
        <%= f.text_field :title %>

        <%= f.label "Recipe Chosen For Review:" %>
        <%= f.collection_select :recipe_id, Recipe.all, :id, :name do |mi| %>
        <% end %>
        
        <%= f.label "Review:" %>
        <%= f.text_area :review_text, rows: 20 %>
        
        <%= f.label :rating %>
        
  <div class="star-rating" id="star-rating-2"> <span class="fa fa-star-o" data-rating="1">1</span>
 <span class="fa fa-star-o" data-rating="2"/>2</span>
 <span class="fa fa-star-o" data-rating="3"/>3</span>
 <span class="fa fa-star-o" data-rating="4"/>4</span>
 <span class="fa fa-star-o" data-rating="5"/>5</span>

    <input type="hidden" name="rating-stars" class="rating-value" value=1 />
    <span class="rating-value">
    <%= f.hidden_field :rating %>
    </span>
</div>

      
        <%= f.submit(@review.new_record? ? 'Create Review' : 'Edit Review', class: "btn btn-success") %>  
     <% end %>
  </div>
</div>

<script>
var $star_rating = $('.star-rating .fa');

var SetRatingStar = function () {
    return $star_rating.each(function () {
        if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
            return $(this).removeClass('fa-star-o').addClass('fa-star');
        } else {
            return $(this).removeClass('fa-star').addClass('fa-star-o');
        }
    });
};

$star_rating.on('click', function () {
    $(this).parent().find('input').val($(this).data('rating')); // <- edited line
    return SetRatingStar();
});

</script>

app/views/reviews/edit.html.erb
<%= render 'shared/page_title', title: "Edit Review" %>
<%= render 'form' %>

app/views/reviews/index.html.erb
<%= render 'shared/page_title', title: "All Reviews" %>

<ul class="nav nav-tabs">
  <li>
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
   <li class="active">
    <%= link_to "Reviews", reviews_path %>
  </li>
</ul>


<%= will_paginate @reviews %>

<% @reviews.each do |review| %>
  <div class="row">
      
      
      <div class="col-md-2">
        
        <section class="chef_info center">
         <%= link_to gravatar_for(review.chef, size: 100), chef_path(review.chef) %>
         <h5>Chef name: <%= review.chef.chefname %></h5>
        </section>
       </div>
  
    <div class="col-lg-6 well">
     <h4><%= link_to review.title, review_path(review) %></h4>
     <p><%= review.review_text %></p>
        <span class="quiet"><small>created: <%= time_ago_in_words(review.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated <%= time_ago_in_words(review.updated_at) %> ago</small></span>
        <p>Rating:</p>
          <% if review.rating == 5 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <span class="fa fa-star" data-rating="3"></span>
    <span class="fa fa-star" data-rating="4"></span>
    <span class="fa fa-star" data-rating="5"></span>
    <% end %>
    
    <% if review.rating == 4 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <span class="fa fa-star" data-rating="3"></span>
    <span class="fa fa-star" data-rating="4"></span>
    <% end %>
    
    <% if review.rating == 3 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <span class="fa fa-star" data-rating="3"></span>
    <% end %>
    
    <% if review.rating == 2 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <% end %>
    
    <% if review.rating == 1 %>
    <span class="fa fa-star" data-rating="1"></span>
    <% end %>
     </p>
    </div>
    
  </div>
<% end %>

<%= will_paginate %>

app/views/reviews/new.html.erb
<%= render 'shared/page_title', title: "Create a new review" %>

<%= render 'form' %>

app/views/reviews/show.html.erb
<%= render 'shared/page_title', title: @review.title %>
<div class="row">
   <div class="col-md-4 pull-right">
     <%= link_to gravatar_for(@review.chef, size: 200), chef_path(@review.chef) %>
     <p>
       <h5>Brought to you by: <%= @review.chef.chefname %></h5>
     </p>
   </div>
   <div class="col-md-8">
     <% if logged_in? and @review.chef == current_user || current_user.admin? %>
     <%= link_to "Edit this Review", edit_review_path(@review), class: "btn btn-success pull-right" %> 
      <% end %>
     <div class="show_recipe">
      <%= image_tag(@review.recipe.picture.url, class: "gravatar") if @review.recipe.picture? %>   
    </div>
      <% if logged_in? and current_user.admin? %>
       <%= link_to "[Delete Review]", @review, method: :delete, data: {confirm: "Are you sure?" } %>
      <% end %>
     <div class="well">
      <strong>Recipe:</strong>
      <%= simple_format(@review.recipe.name) %> 
      <p>
      <strong>Review:</strong>
      </p>
      <%= simple_format(@review.review_text) %>
      
      </string>Rating:</strong>

    <% if @review.rating == 5 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <span class="fa fa-star" data-rating="3"></span>
    <span class="fa fa-star" data-rating="4"></span>
    <span class="fa fa-star" data-rating="5"></span>
    <% end %>
    
    <% if @review.rating == 4 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <span class="fa fa-star" data-rating="3"></span>
    <span class="fa fa-star" data-rating="4"></span>
    <% end %>
    
    <% if @review.rating == 3 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <span class="fa fa-star" data-rating="3"></span>
    <% end %>
    
    <% if @review.rating == 2 %>
    <span class="fa fa-star" data-rating="1"></span>
    <span class="fa fa-star" data-rating="2"></span>
    <% end %>
    
    <% if @review.rating == 1 %>
    <span class="fa fa-star" data-rating="1"></span>
    <% end %>
    
    
    
</div>

<h5><%= link_to 'Return to Reviews listing', reviews_path, class: "btn btn-warning btn-small" %>   </h5>